name: Builder

on:
  push:
    branches:
      - main
    paths:
      - 'tailscale/**'
      - '.github/workflows/builder.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'tailscale/**'
      - '.github/workflows/builder.yaml'

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build ${{ matrix.arch }} tailscale add-on
    strategy:
      matrix:
        arch: ["aarch64", "amd64"]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./tailscale"

      - name: Set build mode
        id: build_mode
        run: |
          echo "image=$(echo ${{ steps.info.outputs.image }} | cut -d'/' -f3)" >> $GITHUB_OUTPUT
          if [[ -z "${{ github.head_ref }}" ]] && [[ "${{ github.event_name }}" == "push" ]]; then
            echo "publish=true" >> $GITHUB_OUTPUT
          else
            echo "publish=false" >> $GITHUB_OUTPUT
          fi

      - name: Login to GitHub Container Registry
        if: steps.build_mode.outputs.publish == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tailscale add-on
        uses: home-assistant/builder@2025.09.0
        with:
          args: |
            ${{ steps.build_mode.outputs.publish == 'false' && '--test' || '' }} \
            --${{ matrix.arch }} \
            --target /data/tailscale \
            --image "${{ steps.build_mode.outputs.image }}" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon
