name: Builder

on:
  push:
    branches:
      - main
    paths:
      - 'tailscale/**'
      - '.github/workflows/builder.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'tailscale/**'
      - '.github/workflows/builder.yaml'

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build ${{ matrix.arch }} tailscale add-on
    strategy:
      matrix:
        arch: ["aarch64", "amd64"]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./tailscale"

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tailscale add-on
        uses: home-assistant/builder@2025.11.0
        with:
          args: |
            ${{ github.event_name == 'pull_request' && '--test' || '' }} \
            --${{ matrix.arch }} \
            --target /data/tailscale \
            --image "$(echo ${{ steps.info.outputs.image }} | cut -d'/' -f3)" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon

  cleanup:
    runs-on: ubuntu-24.04
    name: Clean up old container images
    needs: build
    if: github.event_name == 'push'
    strategy:
      matrix:
        arch: ["aarch64", "amd64"]
    permissions:
      packages: write

    steps:
      - name: Delete untagged images
        uses: actions/delete-package-versions@v5
        with:
          package-name: addon-tailscale-${{ matrix.arch }}
          package-type: container
          delete-only-untagged-versions: true

      - name: Keep only 5 most recent tagged versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: addon-tailscale-${{ matrix.arch }}
          package-type: container
          min-versions-to-keep: 5
